[workspace]
members = [
  "crates/aos-air-types",
  "crates/aos-air-exec",
  "crates/aos-cbor",
  "crates/aos-store",
  "crates/aos-wasm-abi",
  "crates/aos-wasm",
  "crates/aos-effects",
  "crates/aos-kernel",
  "crates/aos-wasm-sdk",
  "crates/aos-testkit",
  "crates/aos-cli",
  "crates/aos-examples",
  "examples/00-counter/reducer",
  "examples/01-hello-timer/reducer",
]
resolver = "2"
