[workspace]

[package]
name = "fetch-notify-reducer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aos-air-exec = { path = "../../../crates/aos-air-exec" }
aos-wasm-sdk = { path = "../../../crates/aos-wasm-sdk" }
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
