[package]
name = "aos-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
aos-air-types = { path = "../aos-air-types" }
aos-kernel = { path = "../aos-kernel" }
aos-host = { path = "../aos-host" }
aos-store = { path = "../aos-store" }
aos-wasm-build = { path = "../aos-wasm-build" }
camino = "1"
clap = { version = "4", features = ["derive"] }
serde_json = "1"
serde_cbor = "0.11"
tokio = { version = "1", features = ["full"] }
anyhow = "1"

[[bin]]
name = "aos"
path = "src/main.rs"
