[package]
name = "aos-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
aos-wasm-abi = { path = "../aos-wasm-abi" }
anyhow = "1"
wasmtime = "36.0.3"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
wat = "1"
