[workspace]

[package]
name = "chain-comp-reducer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aos-air-exec = { path = "../../../crates/aos-air-exec" }
aos-wasm-abi = { path = "../../../crates/aos-wasm-abi" }
indexmap = "2"
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
