[workspace]

[package]
name = "demiurge-workflow"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aos-agent-sdk = { path = "../../../crates/aos-agent-sdk" }
aos-wasm-sdk = { path = "../../../crates/aos-wasm-sdk" }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_cbor = { version = "0.11", default-features = false }
