[workspace]

[package]
name = "demiurge-reducer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aos-wasm-sdk = { path = "../../../crates/aos-wasm-sdk" }
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
serde_bytes = "0.11"
serde_json = { version = "1", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10", default-features = false }
hex = { version = "0.4", default-features = false }

[dev-dependencies]
aos-wasm-abi = { path = "../../../crates/aos-wasm-abi" }
